//const String TITLE_APPBAR = 'Lista de Tareas';
const String TITULO_APPBAR = 'Lista de Tareas';
//const String EMPTY_LIST = 'No hay tareas';
const String LISTA_VACIA = 'No hay tareas';
//const String TASK_TYPE_LABEL = 'Tipo: ';
const String TIPO_TAREA = 'Tipo: ';
const String PASOS_TITULO = 'Pasos para completar:';
const String FECHA_LIMITE = 'Fecha límite:';
const String TAREA_ELIMINADA = 'Tarea eliminada';