//const String TITLE_APPBAR = 'Lista de Tareas';
const String tituloAppbar = 'Lista de Tareas';
//const String EMPTY_LIST = 'No hay tareas';
const String listaVacia = 'No hay tareas';
//const String TASK_TYPE_LABEL = 'Tipo: ';
const String tipoTarea = 'Tipo: ';
const String pasosTitulo = 'Pasos para completar:';
const String fechaLimite = 'Fecha límite:';
const String tareaEliminada = 'Tarea eliminada';